// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTGZa2_9P7G2mq3EpUraE9WzUk1C-wcMg',
    appId: '1:535222019003:web:1c2b2227cc2ff0d04b5a9e',
    messagingSenderId: '535222019003',
    projectId: 'transitrack-709f1',
    authDomain: 'transitrack-709f1.firebaseapp.com',
    storageBucket: 'transitrack-709f1.appspot.com',
    measurementId: 'G-NVGW2FS7SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVi1awMUCpMK6P-AejbbG0Ga2jBtD13Vo',
    appId: '1:535222019003:android:f10efc7f51e4c6494b5a9e',
    messagingSenderId: '535222019003',
    projectId: 'transitrack-709f1',
    storageBucket: 'transitrack-709f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8AL1U9r7IdOOfeRoBPLT5AqAPE89V4uQ',
    appId: '1:535222019003:ios:aa25956245ff57214b5a9e',
    messagingSenderId: '535222019003',
    projectId: 'transitrack-709f1',
    storageBucket: 'transitrack-709f1.appspot.com',
    iosClientId: '535222019003-i62qpji6e74q941opglmqeoe0vi1lj6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.transitrackWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8AL1U9r7IdOOfeRoBPLT5AqAPE89V4uQ',
    appId: '1:535222019003:ios:aa25956245ff57214b5a9e',
    messagingSenderId: '535222019003',
    projectId: 'transitrack-709f1',
    storageBucket: 'transitrack-709f1.appspot.com',
    iosClientId: '535222019003-i62qpji6e74q941opglmqeoe0vi1lj6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.transitrackWeb',
  );
}
